from src.agent_wrapper import AgentResponse, ArmorGuard
from src.agents.echo_agent import EchoAgent

# --- Protocol attributes ---


def test_has_required_protocol_attributes():
    # TC-010-01
    agent = EchoAgent()
    assert hasattr(agent, "session_id")
    assert hasattr(agent, "retrieved_context")
    assert hasattr(agent, "tool_calls")


def test_retrieved_context_empty_at_construction():
    # TC-010-02
    assert EchoAgent().retrieved_context == []


def test_tool_calls_empty_at_construction():
    # TC-010-03
    assert EchoAgent().tool_calls == []


def test_session_id_is_nonempty_string_when_autogenerated():
    # TC-010-04
    agent = EchoAgent()
    assert isinstance(agent.session_id, str)
    assert len(agent.session_id) > 0


def test_custom_session_id_stored_as_is():
    # TC-010-05
    agent = EchoAgent(session_id="my-session")
    assert agent.session_id == "my-session"


def test_two_instances_get_distinct_session_ids():
    # TC-010-06
    a = EchoAgent()
    b = EchoAgent()
    assert a.session_id != b.session_id


# --- process_request ---


def test_process_request_echoes_input():
    # TC-010-07
    result = EchoAgent().process_request("hello")
    assert isinstance(result, AgentResponse)
    assert result.text == "echo: hello"


def test_process_request_empty_string():
    # TC-010-08
    result = EchoAgent().process_request("")
    assert result.text == "echo: "


def test_lists_remain_empty_after_call():
    # TC-010-09
    agent = EchoAgent()
    agent.process_request("x")
    assert agent.retrieved_context == []
    assert agent.tool_calls == []


# --- ArmorGuard integration ---


def test_echo_agent_works_inside_armor_guard():
    # TC-010-10
    result = ArmorGuard(EchoAgent(), armor_client=None).process("ping")
    assert result == "echo: ping"
