from src.agent_wrapper import AgentResponse, ArmorGuard
from src.agents.multi_turn_agent import MultiTurnAgent


def stub_generate(answer: str):
    def _generate(query: str, history: list[dict]) -> str:
        return answer

    return _generate


# --- Protocol attributes ---


def test_has_required_protocol_attributes():
    # TC-014-01
    agent = MultiTurnAgent(stub_generate(""))
    assert hasattr(agent, "session_id")
    assert hasattr(agent, "retrieved_context")
    assert hasattr(agent, "tool_calls")


def test_retrieved_context_empty_at_construction():
    # TC-014-02
    assert MultiTurnAgent(stub_generate("")).retrieved_context == []


def test_tool_calls_empty_at_construction():
    # TC-014-03
    assert MultiTurnAgent(stub_generate("")).tool_calls == []


def test_session_id_is_nonempty_string_when_autogenerated():
    # TC-014-04
    agent = MultiTurnAgent(stub_generate(""))
    assert isinstance(agent.session_id, str)
    assert len(agent.session_id) > 0


def test_custom_session_id_stored_as_is():
    # TC-014-05
    agent = MultiTurnAgent(stub_generate(""), session_id="s1")
    assert agent.session_id == "s1"


def test_two_instances_get_distinct_session_ids():
    # TC-014-06
    a = MultiTurnAgent(stub_generate(""))
    b = MultiTurnAgent(stub_generate(""))
    assert a.session_id != b.session_id


# --- process_request return value ---


def test_process_request_returns_agent_response():
    # TC-014-07
    assert isinstance(MultiTurnAgent(stub_generate("ans")).process_request("q"), AgentResponse)


def test_process_request_text_equals_generate_output():
    # TC-014-08
    assert MultiTurnAgent(stub_generate("the answer")).process_request("q").text == "the answer"


# --- History management ---


def test_history_empty_at_construction():
    # TC-014-09
    assert MultiTurnAgent(stub_generate(""))._history == []


def test_history_has_user_and_assistant_after_one_call():
    # TC-014-10
    agent = MultiTurnAgent(stub_generate("hi"))
    agent.process_request("hello")
    assert agent._history == [
        {"role": "user", "content": "hello"},
        {"role": "assistant", "content": "hi"},
    ]


def test_history_grows_to_four_after_two_calls():
    # TC-014-11
    agent = MultiTurnAgent(stub_generate("r"))
    agent.process_request("a")
    agent.process_request("b")
    assert len(agent._history) == 4


def test_history_roles_are_user_or_assistant_only():
    # TC-014-12
    agent = MultiTurnAgent(stub_generate("r"))
    agent.process_request("a")
    agent.process_request("b")
    assert all(e["role"] in {"user", "assistant"} for e in agent._history)


def test_retrieved_context_stays_empty_after_calls():
    # TC-014-13
    agent = MultiTurnAgent(stub_generate("r"))
    agent.process_request("q")
    assert agent.retrieved_context == []


def test_tool_calls_stays_empty_after_calls():
    # TC-014-14
    agent = MultiTurnAgent(stub_generate("r"))
    agent.process_request("q")
    assert agent.tool_calls == []


# --- generate wiring ---


def test_generate_called_with_user_input():
    # TC-014-15
    received_queries: list[str] = []

    def _generate(query: str, history: list[dict]) -> str:
        received_queries.append(query)
        return "r"

    MultiTurnAgent(_generate).process_request("my input")
    assert received_queries == ["my input"]


def test_generate_receives_history_including_current_user_message_on_second_call():
    # TC-014-16
    received_histories: list = []

    def _generate(query: str, history: list[dict]) -> str:
        received_histories.append(list(history))
        return "reply"

    agent = MultiTurnAgent(_generate)
    agent.process_request("first")
    agent.process_request("second")

    second_history = received_histories[1]
    assert {"role": "user", "content": "first"} in second_history
    assert {"role": "assistant", "content": "reply"} in second_history
    assert {"role": "user", "content": "second"} in second_history


def test_history_does_not_bleed_between_instances():
    # TC-014-17
    a = MultiTurnAgent(stub_generate("ra"))
    b = MultiTurnAgent(stub_generate("rb"))
    a.process_request("hello")
    b.process_request("world")
    assert len(a._history) == 2
    assert len(b._history) == 2
    assert a._history[0]["content"] == "hello"
    assert b._history[0]["content"] == "world"


# --- ArmorGuard integration ---


def test_multi_turn_agent_works_inside_armor_guard():
    # TC-014-18
    result = ArmorGuard(MultiTurnAgent(stub_generate("reply")), armor_client=None).process("ping")
    assert result == "reply"
