from src.agent_wrapper import AgentResponse, ArmorGuard
from src.agents.rag_agent import RAGAgent


def stub_retrieve(docs: list[str]):
    def _retrieve(query: str) -> list[str]:
        return docs

    return _retrieve


def stub_generate(answer: str):
    def _generate(query: str, context: list[str]) -> str:
        return answer

    return _generate


# --- Protocol attributes ---


def test_has_required_protocol_attributes():
    # TC-012-01
    agent = RAGAgent(stub_retrieve([]), stub_generate(""))
    assert hasattr(agent, "session_id")
    assert hasattr(agent, "retrieved_context")
    assert hasattr(agent, "tool_calls")


def test_retrieved_context_empty_at_construction():
    # TC-012-02
    assert RAGAgent(stub_retrieve([]), stub_generate("")).retrieved_context == []


def test_tool_calls_empty_at_construction():
    # TC-012-03
    assert RAGAgent(stub_retrieve([]), stub_generate("")).tool_calls == []


def test_session_id_is_nonempty_string_when_autogenerated():
    # TC-012-04
    agent = RAGAgent(stub_retrieve([]), stub_generate(""))
    assert isinstance(agent.session_id, str)
    assert len(agent.session_id) > 0


def test_custom_session_id_stored_as_is():
    # TC-012-05
    agent = RAGAgent(stub_retrieve([]), stub_generate(""), session_id="s1")
    assert agent.session_id == "s1"


def test_two_instances_get_distinct_session_ids():
    # TC-012-06
    a = RAGAgent(stub_retrieve([]), stub_generate(""))
    b = RAGAgent(stub_retrieve([]), stub_generate(""))
    assert a.session_id != b.session_id


# --- process_request return value ---


def test_process_request_returns_agent_response():
    # TC-012-07
    agent = RAGAgent(stub_retrieve([]), stub_generate("ans"))
    assert isinstance(agent.process_request("q"), AgentResponse)


def test_process_request_text_equals_generate_output():
    # TC-012-08
    agent = RAGAgent(stub_retrieve([]), stub_generate("the answer"))
    assert agent.process_request("q").text == "the answer"


# --- process_request side effects ---


def test_retrieved_context_populated_after_call():
    # TC-012-09
    agent = RAGAgent(stub_retrieve(["chunk1", "chunk2"]), stub_generate(""))
    agent.process_request("q")
    assert agent.retrieved_context == ["chunk1", "chunk2"]


def test_retrieved_context_resets_on_second_call():
    # TC-012-10
    call_count = 0

    def _retrieve(query: str) -> list[str]:
        nonlocal call_count
        call_count += 1
        return ["a"] if call_count == 1 else ["b"]

    agent = RAGAgent(_retrieve, stub_generate(""))
    agent.process_request("first")
    agent.process_request("second")
    assert agent.retrieved_context == ["b"]


def test_tool_calls_stays_empty_after_call():
    # TC-012-11
    agent = RAGAgent(stub_retrieve(["x"]), stub_generate("ans"))
    agent.process_request("q")
    assert agent.tool_calls == []


# --- retrieve/generate wiring ---


def test_retrieve_called_with_user_query():
    # TC-012-12
    received: list[str] = []

    def _retrieve(query: str) -> list[str]:
        received.append(query)
        return []

    RAGAgent(_retrieve, stub_generate("")).process_request("my query")
    assert received == ["my query"]


def test_generate_called_with_query_and_docs():
    # TC-012-13
    received: list = []

    def _generate(query: str, context: list[str]) -> str:
        received.append((query, context))
        return "ok"

    RAGAgent(stub_retrieve(["doc1"]), _generate).process_request("my query")
    assert received == [("my query", ["doc1"])]


# --- ArmorGuard integration ---


def test_rag_agent_works_inside_armor_guard():
    # TC-012-14
    result = ArmorGuard(RAGAgent(stub_retrieve([]), stub_generate("the answer")), armor_client=None).process("q")
    assert result == "the answer"
