from src.agent_wrapper import AgentResponse, ArmorGuard
from src.agents.tool_use_agent import ToolUseAgent


def stub_decide(specs: list[dict]):
    def _decide(query: str) -> list[dict]:
        return specs

    return _decide


def stub_execute(result: str):
    def _execute(tool: str, args: dict) -> str:
        return result

    return _execute


def stub_generate(answer: str):
    def _generate(query: str, tool_calls: list[dict]) -> str:
        return answer

    return _generate


# --- Protocol attributes ---


def test_has_required_protocol_attributes():
    # TC-013-01
    agent = ToolUseAgent(stub_decide([]), stub_execute(""), stub_generate(""))
    assert hasattr(agent, "session_id")
    assert hasattr(agent, "retrieved_context")
    assert hasattr(agent, "tool_calls")


def test_retrieved_context_empty_at_construction():
    # TC-013-02
    assert ToolUseAgent(stub_decide([]), stub_execute(""), stub_generate("")).retrieved_context == []


def test_tool_calls_empty_at_construction():
    # TC-013-03
    assert ToolUseAgent(stub_decide([]), stub_execute(""), stub_generate("")).tool_calls == []


def test_session_id_is_nonempty_string_when_autogenerated():
    # TC-013-04
    agent = ToolUseAgent(stub_decide([]), stub_execute(""), stub_generate(""))
    assert isinstance(agent.session_id, str)
    assert len(agent.session_id) > 0


def test_custom_session_id_stored_as_is():
    # TC-013-05
    agent = ToolUseAgent(stub_decide([]), stub_execute(""), stub_generate(""), session_id="s1")
    assert agent.session_id == "s1"


def test_two_instances_get_distinct_session_ids():
    # TC-013-06
    a = ToolUseAgent(stub_decide([]), stub_execute(""), stub_generate(""))
    b = ToolUseAgent(stub_decide([]), stub_execute(""), stub_generate(""))
    assert a.session_id != b.session_id


# --- process_request return value ---


def test_process_request_returns_agent_response():
    # TC-013-07
    agent = ToolUseAgent(stub_decide([]), stub_execute(""), stub_generate("ans"))
    assert isinstance(agent.process_request("q"), AgentResponse)


def test_process_request_text_equals_generate_output():
    # TC-013-08
    agent = ToolUseAgent(stub_decide([]), stub_execute(""), stub_generate("the answer"))
    assert agent.process_request("q").text == "the answer"


# --- tool_calls side-effects ---


def test_tool_calls_populated_after_call():
    # TC-013-09
    agent = ToolUseAgent(
        stub_decide([{"tool": "search", "args": {"q": "x"}}]),
        stub_execute("result1"),
        stub_generate(""),
    )
    agent.process_request("q")
    assert agent.tool_calls == [{"tool": "search", "args": {"q": "x"}, "result": "result1"}]


def test_multiple_tools_recorded_in_order():
    # TC-013-10
    call_num = 0

    def _execute(tool: str, args: dict) -> str:
        nonlocal call_num
        call_num += 1
        return f"r{call_num}"

    agent = ToolUseAgent(
        stub_decide([{"tool": "t1", "args": {}}, {"tool": "t2", "args": {}}]),
        _execute,
        stub_generate(""),
    )
    agent.process_request("q")
    assert len(agent.tool_calls) == 2
    assert agent.tool_calls[0]["result"] == "r1"
    assert agent.tool_calls[1]["result"] == "r2"


def test_tool_calls_resets_on_second_call():
    # TC-013-11
    call_num = 0

    def _decide(query: str) -> list[dict]:
        nonlocal call_num
        call_num += 1
        return [{"tool": "t", "args": {}}] if call_num == 1 else []

    agent = ToolUseAgent(_decide, stub_execute("r"), stub_generate(""))
    agent.process_request("first")
    agent.process_request("second")
    assert agent.tool_calls == []


def test_retrieved_context_stays_empty_after_call():
    # TC-013-12
    agent = ToolUseAgent(stub_decide([{"tool": "t", "args": {}}]), stub_execute("r"), stub_generate(""))
    agent.process_request("q")
    assert agent.retrieved_context == []


def test_zero_tools_decided_empty_tool_calls_response_returned():
    # TC-013-13
    agent = ToolUseAgent(stub_decide([]), stub_execute(""), stub_generate("ok"))
    result = agent.process_request("q")
    assert agent.tool_calls == []
    assert result.text == "ok"


# --- callable wiring ---


def test_decide_tools_called_with_user_query():
    # TC-013-14
    received: list[str] = []

    def _decide(query: str) -> list[dict]:
        received.append(query)
        return []

    ToolUseAgent(_decide, stub_execute(""), stub_generate("")).process_request("my query")
    assert received == ["my query"]


def test_execute_tool_called_with_tool_name_and_args():
    # TC-013-15
    received: list = []

    def _execute(tool: str, args: dict) -> str:
        received.append((tool, args))
        return "r"

    ToolUseAgent(
        stub_decide([{"tool": "search", "args": {"q": "x"}}]),
        _execute,
        stub_generate(""),
    ).process_request("q")
    assert received == [("search", {"q": "x"})]


def test_generate_called_with_query_and_completed_tool_calls():
    # TC-013-16
    received: list = []

    def _generate(query: str, tool_calls: list[dict]) -> str:
        received.append((query, tool_calls))
        return "ok"

    ToolUseAgent(
        stub_decide([{"tool": "search", "args": {"q": "x"}}]),
        stub_execute("r"),
        _generate,
    ).process_request("my query")
    assert received == [("my query", [{"tool": "search", "args": {"q": "x"}, "result": "r"}])]


# --- ArmorGuard integration ---


def test_tool_use_agent_works_inside_armor_guard():
    # TC-013-17
    result = ArmorGuard(
        ToolUseAgent(stub_decide([]), stub_execute(""), stub_generate("the answer")),
        armor_client=None,
    ).process("q")
    assert result == "the answer"
